config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :posts  do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :index, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :activities, only: [:index]
end

app/models/comment.rb
class Comment < ApplicationRecord
  include PublicActivity::Common
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
  validate :comment_exceed_length

  private

  def comment_exceed_length
    errors.add(:body, "exceeds maximum character length") if body.length > 1000
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def index
    @comments = @post.comments.order(created_at: :desc)
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      @comment.create_activity :create, owner: current_user, recipient: @post.user
    else
      flash[:danger] = @comment.errors.full_messages.first
    end
    render :index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    render :index
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id)
  end

end

app/views/comments/_form.html.erb
<%= form_with(model: [post, Comment.new] ) do |f| %>
  <div class="form-group">
    <div class="control-label col-xs-2">
      <%= f.label 'Comment' %>
    </div>
    <div class="col-xs-8">
      <%= f.text_area :body, class: "form-control", size: "50x1", maxlength: "300" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
      <%= f.submit class: 'btn btn-primary btn-md' %>
    </div>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% if comments.present? %> 
  <% comments.each do |comment| %>
    <p><strong><%= comment.user.username %></strong> <%= comment.body %></p>
    <% if comment.user == current_user %>
      <p><%= link_to "Delete Comment", post_comment_path(post, comment), method: :delete, remote: true, class: 'btn btn-danger btn-sm' %></p>
    <% end %>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area_<%= @post.id %>").html("<%= j(render partial: 'comments/index', locals: {post: @post, comments: @post.comments}) %>")
$("textarea").val('')