config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :posts  do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :index, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :activities, only: [:index]
end

app/models/like.rb
class Like < ApplicationRecord
  include PublicActivity::Common
  belongs_to :post
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @like.create_activity :create, owner: current_user, recipient: @post.user
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @post.reload
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/views/likes/_like.html.erb
<% pre_like = post.likes.find_by(user_id: current_user.id) %>
<% if pre_like.present? %>
  <%= link_to post_like_path(post_id: post.id ,id: pre_like), method: :delete, remote: true do %>
    <p><%= fa_icon("heart") %> <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
  <% end %>
<% else %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true do %>
      <p><%= fa_icon("heart-o") %> <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <% end %>
<% end %>

app/views/likes/create.js.erb
$('#like_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#like_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");