config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :posts  do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :index, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :activities, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_reader
  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :passive_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validate :image_invalid_type, :image_too_big
  validates :username, :fullname, :email, presence: true
  validates :username, uniqueness: true
  validates_length_of :username, :fullname, minimum: 6, maximum: 50
  validates_length_of :phone_number, maximum: 11
  validates_length_of :email, :website, maximum: 250
  validates_length_of :bio, maximum: 150

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
      user.image = auth.info.image
      user.fullname = auth.info.name
    end
  end

  # Follows a user
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current is following the other user
  def following?(other_user)
    following.include?(other_user)
  end

  private

  def image_invalid_type
    return unless profile_image.attached?

    unless profile_image.content_type == "image/png" || profile_image.content_type == "image/jpeg"
      errors.add(:profile_image, "can only be jpeg or png")
    end
  end

  def image_too_big
    return unless profile_image.attached?

    errors.add(:profile_image, "is too big") if profile_image.blob.byte_size > 2000000
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to new_user_registration_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # def index
  # end

  def show
    @title = "User"
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 9)
  end

  # def new
  # end

  def profile
    redirect_to user_path(current_user)
  end

  def edit
    @title = "Edit User"
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to user_path(@user)
    else
      flash[:danger] = @user.errors.full_messages.first
      render "edit"
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:id, :username, :email, :password,
      :bio, :fullname, :website, :phone_number, :gender, :image, :profile_image)
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary my-2" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_post.html.erb
<% if obj.present? %>
  <% obj.each do |post| %>
    <style>
    #username {
      margin: auto;
    }
    #post-image {
      width: 100%;
      height: 345px;
    }
    </style>
    <div class="col-md-4">
      <div class="card mb-4">
        <% if post.post_image.attached? %>
          <a href="#" data-toggle="modal" data-target="#modal-<%= post.id %>">
            <%= image_tag post.post_image, size: "293x293" %>
          </a>
          <div id="modal-<%= post.id %>" class="modal hide fade" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <a href="#" class="close" data-dismiss="modal">&#215;</a>
                <div class="row">
                  <div class="col-md-7">
                    <%= image_tag post.post_image, class: "image", id: "post-image"%>
                  </div>
                  <div class="col-md-5" id="post-content">
                    <div class="description my-2">
                      <strong><%= post.user.username %> </strong> <%= post.description %>
                    </div>
                    <% if post.comments.present? %>
                      <% post.comments.each do |comment| %>
                        <div class="mb-2" id="comments_area_<%= post.id %>">
                          <strong><%= comment.user.username %></strong> <%= comment.body %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>
                <%= link_to('Go to post', post_path(post), class: "btn btn-outline-secondary") %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <strong><%= @user.posts.count %></strong> posts
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-outline-secondary my-2" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, @title)%>
<div class='justify-content-center row'>
  <div class='col-md-12 offset-md-4'>
    <h2>Edit Profile</h2>
    <%= form_with(model: @user, local: true) do |f| %>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :profile_image %> <br />
        </div>
        <div class="col-md-8">
          <%= f.file_field :profile_image, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :fullname %><span style="color:red">＊</span>
        </div>
        <div class="col-md-8">
          <%= f.text_field :fullname, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :username %><span style="color:red">＊</span>
        </div>
        <div class="col-md-8">
          <%= f.text_field :username, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :website %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :website, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :bio %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :bio, class: "form-control", size: "20x5", maxlength: "300", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :email, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :phone_number %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :phone_number, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :gender %>
        </div>
        <div class="col-md-8">
          <%= f.select :gender, ['Not Specified','Male', 'Female'], class: "form-control", autofocus: true %> 
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= link_to('Change Password', edit_user_registration_path(current_user), class: "btn btn-outline-secondary") %>
          <%= link_to('Delete Account', registration_path(current_user), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-outline-danger") %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10" id="edit-sub-btn">
          <%= f.submit class: 'btn btn-primary btn-md' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @title) %>
<%= render "common/showstyling" %>
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading"><%= @user.username %></h1>
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image, style: 'width:150px;height:150px;border-radius: 50%;' %>
      <% elsif @user.image.present? %>
        <%= image_tag @user.image, style: 'width:150px;height:150px;border-radius: 50%;' %>
      <% else %>
        <%= image_tag 'default_profile_picture.jpg', style: 'width:150px;height:150px;border-radius: 50%;' %>
      <% end %>
      <p>
      <%= render 'stats' %>
      </p>
      <p class="lead text-muted">
        <%= @user.fullname %><br>
        <%= @user.bio %><br>
        <%= @user.website %></p>
      <p>
        <% if current_user == @user %>
          <%= link_to('Edit Profile', edit_user_path(current_user), class: "btn btn-outline-secondary my-2") %>
        <% else %>
          <%= render 'follow_form' %>
        <% end %>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <%= render 'post', obj: @posts %>
      </div>
      <ul class="list-unstyled list-inline text-center py-2">
        <li class="list-inline-item">
          <div class="digg_pagination">
            <%= will_paginate @posts %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</main>

app/views/users/show_follow.html.erb
<% provide(:title, @title)%>
<%= render "common/notificationsstyling" %>
<main role="main" class="container">
  <div class="d-flex align-items-center p-3 my-3 text-black-50 bg-light rounded shadow-sm">
    <% if current_user.profile_image.attached? %>
      <%= image_tag current_user.profile_image, class: "mr-3", size: "48x48" %>
    <% elsif current_user.image.present? %>
      <%= image_tag current_user.image, class: "mr-3", size: "48x48" %>
    <% else %>
      <%= image_tag 'default_profile_picture.jpg', class: "mr-3", size: "48x48" %>
    <% end %>
    <div class="lh-100">
      <h6 class="mb-0 text-black lh-100"><%= current_user.username %> <%= @title %> list</h6>
    </div>
  </div>

  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0"><%= @title %> list</h6>
      <% if @users.any? %>
        <% @users.each do |user| %>
          <div class="media text-muted pt-3">
            <% if user.profile_image.attached? %>
              <%= image_tag user.profile_image, class: "mr-2 rounded", size: '32x32' %>
            <% elsif user.image.present? %>
              <%= image_tag user.image, class: "mr-2 rounded", size: '32x32' %>
            <% else %>
              <%= image_tag 'default_profile_picture.jpg', class: "mr-2 rounded", size: '32x32' %>
            <% end %>
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              <strong class="d-block text-gray-dark"><%= link_to user.username, user %></strong>
            </p>
          </div>
        <% end %>
      <% end %>
      <center><%= link_to "Go Back", @user, class: "btn btn-outline-secondary my-3" %></center>
      <ul class="list-unstyled list-inline text-center py-2">
        <li class="list-inline-item">
          <div class="digg_pagination">
            <%= will_paginate @users %>
          </div>
        </li>
      </ul>
  </div>
</main>