config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :posts  do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :index, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :activities, only: [:index]
end

app/views/common/_errormessages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="<%= name %>">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= msg %>
  </div>
<% end %>

app/views/common/_footer.html.erb
<footer class="fixed-bottom page-footer font-small unique-color-dark pt-2 bg-light">
    <div class="container">
			<ul class="list-unstyled list-inline text-center pt-1">
        <li class="list-inline-item">
          <%= link_to('Upload Picture', new_post_path, class: "btn btn-outline-success my-2 my-sm-0") %>
        </li>
      </ul>
    </div>
    <div class="footer-copyright text-center pb-1">© 2019 Copyright:
      <a href="#"> Rutger Taal</a>
    </div>
</footer>

app/views/common/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to posts_path do %>
      <%= image_tag "instagram_logo.png", style: "width:100px", class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if current_user.present? %>
          <li class="nav-item">
            <%= link_to(posts_path, class: "nav-link") do %>
              <i class="fa fa-instagram fa-lg"></i>
            <% end %>
          </li>
        <% end %>
        <% if current_user.present? %>
          <li class="nav-item">
            <%= link_to(user_path(current_user), class: "nav-link") do %>
              <i class="fa fa-user fa-lg"></i>
            <% end %>
          </li>
        <% end %>
        <% if current_user.present? %>
          <li class="nav-item">
            <% if (unread = Activity.where(recipient: current_user)&.unread_by(current_user)).present? %>
              <%= link_to(activities_path, class: "nav-link") do %>
                <i class="fa fa-bell fa-lg"></i><span id="badge-notify"> <%= unread.count %> </span>
              <% end %>
            <% else %>
              <%= link_to(activities_path, class: "nav-link") do %>
                <i class="fa fa-bell fa-lg"></i>
              <% end %>
            <% end %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to(destroy_user_session_path, method: :delete, class: "nav-link") do %>
            <i class="fa fa-power-off fa-lg"></i>
          <% end %>
        </li>
      </ul>
      <%= form_tag(posts_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
        <%= text_field_tag :description, params[:description], class: "form-control mr-sm-2", placeholder: "Search" %>
        <%= submit_tag 'Search', name: nil, class: "btn btn-info my-2 my-sm-0" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/common/_notificationsstyling.html.erb
<style>
.text-black-50 { color: rgba(0, 0, 0, 1.0); }

.lh-100 { line-height: 1; }
.lh-125 { line-height: 1.25; }
.lh-150 { line-height: 1.5; }
</style>

app/views/common/_poststyling.html.erb
<style>
#post-image {
  width: 100%;
  height: 345px;
}

.profile {
  border-radius: 50%;
  width: 50px;
  height: 50px;
}

#username {
  margin: auto;
}

@media (max-device-width: 812px)   {
  #post-content {
    margin-bottom: 100px;
  }
}

@media screen and (min-width: 800px) {
  #post-image {
    width: 600px;
    height: 600px;
  }
}


</style>

app/views/common/_showstyling.html.erb
<style>
.jumbotron {
  padding-top: 3rem;
  padding-bottom: 3rem;
  margin-bottom: 0;
  background-color: #fff;
}

.jumbotron p:last-child {
  margin-bottom: 0;
}

.alert.alert-notice {
  background-color: #d4edda;
}

.jumbotron-heading {
  font-weight: 300;
}

.jumbotron .container {
  max-width: 40rem;
}

.card {
  background-color: transparent;
  justify-content: center;
  flex-direction: row;
  border: none;
}

.close {
  text-align: right;
  float: right;
}
</style>